import { ArrowRight, Boxes, CheckCircle2, ScanLine, ShieldCheck, WalletCards } from "lucide-react";
import { loginAction } from "@/app/actions";
import { Logo } from "@/components/logo";

export default async function LoginPage({searchParams}:{searchParams:Promise<{erro?:string}>}){
  const{erro}=await searchParams;
  return <main className="grid min-h-screen bg-[#f5f6fa] lg:grid-cols-[1.08fr_.92fr]">
    <section className="relative hidden overflow-hidden border-r border-[#e4e7ef] bg-white p-12 lg:flex lg:flex-col"><div className="absolute -bottom-40 -left-36 size-[520px] rounded-full bg-[#eef2ff]"/><div className="absolute bottom-10 left-20 size-72 rounded-full border border-[#dfe5ff]"/><div className="absolute right-10 top-20 size-52 rounded-full bg-[#f4f0ff]"/><div className="relative"><Logo/></div><div className="relative my-auto max-w-xl"><span className="mb-7 inline-flex items-center gap-2 rounded-full border border-[#dce4ff] bg-[#f3f6ff] px-3 py-1.5 text-[10px] font-semibold uppercase tracking-[.08em] text-[#5977f4]"><ShieldCheck size={13} strokeWidth={1.8}/>Gestão segura e inteligente</span><h1 className="text-[50px] font-semibold leading-[1.08] tracking-[-.055em] text-[#171925]">Controle sua loja.<br/><span className="text-[#6f7da6]">Venda com confiança.</span></h1><p className="mt-6 max-w-lg text-[15px] leading-7 text-[#858a9c]">Estoque por IMEI, PDV e financeiro conectados em uma experiência simples e profissional.</p><div className="mt-10 grid max-w-lg grid-cols-3 gap-3">{[{icon:ScanLine,label:"IMEI rastreado",color:"#5977f4",bg:"#eef2ff"},{icon:WalletCards,label:"PDV integrado",color:"#8b6df3",bg:"#f4f0ff"},{icon:Boxes,label:"Estoque real",color:"#20b978",bg:"#eaf9f2"}].map(item=><div key={item.label} className="rounded-2xl border border-[#e8eaf1] bg-white p-4 shadow-[0_5px_18px_rgba(24,35,70,.04)]"><span className="grid size-9 place-items-center rounded-xl" style={{color:item.color,background:item.bg}}><item.icon size={18} strokeWidth={1.8}/></span><p className="mt-3 text-[11px] font-medium text-[#565b6d]">{item.label}</p></div>)}</div></div><p className="relative text-[10px] tracking-wide text-[#a0a5b3]">CELLSHOP · SOFTWARE DE GESTÃO</p></section>
    <section className="flex items-center justify-center p-6"><div className="w-full max-w-[420px] rounded-[24px] border border-[#e7e9f0] bg-white p-7 shadow-[0_18px_60px_rgba(34,46,90,.08)] sm:p-9"><div className="mb-9 lg:hidden"><Logo/></div><span className="icon-tile mb-5 size-11 rounded-[14px]"><ShieldCheck size={20} strokeWidth={1.8}/></span><p className="eyebrow mb-2">Acesso seguro</p><h2 className="text-[29px] font-semibold tracking-[-.04em] text-[#1a1c28]">Bem-vindo de volta</h2><p className="mt-2 text-[13px] text-[#8a8f9f]">Use suas credenciais para acessar o sistema.</p>{erro&&<div className="mt-6 rounded-xl border border-[#ffd9df] bg-[#fff3f5] p-3 text-xs text-[#dc465a]">{erro}</div>}<form action={loginAction} className="mt-8 space-y-5"><div><label className="label" htmlFor="email">E-mail corporativo</label><input className="input h-12" id="email" name="email" type="email" autoComplete="username" required/></div><div><label className="label" htmlFor="password">Senha</label><input className="input h-12" id="password" name="password" type="password" autoComplete="current-password" minLength={8} maxLength={128} required/></div><button className="btn-primary h-12 w-full" type="submit">Entrar no CELLSHOP <ArrowRight size={17} strokeWidth={1.8}/></button></form><p className="mt-6 flex items-center justify-center gap-2 text-[10px] text-[#a0a5b3]"><CheckCircle2 size={12} strokeWidth={1.8}/>Sessão criptografada e monitorada</p></div></section>
  </main>;
}
