import { notFound } from "next/navigation";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { Barcode } from "@/components/barcode";
import { PrintButton } from "@/components/print-button";
import { brl } from "@/lib/format";
import { prisma } from "@/lib/prisma";
export const dynamic="force-dynamic";
export default async function LabelPage({params}:{params:Promise<{id:string}>}){const{id}=await params;const unit=await prisma.inventoryUnit.findUnique({where:{id},include:{productVariant:true}});if(!unit)notFound();return <><div className="no-print mb-7 flex items-center justify-between"><Link href="/estoque" className="inline-flex items-center gap-2 text-sm text-zinc-500 hover:text-white"><ArrowLeft size={16}/>Voltar ao estoque</Link><PrintButton/></div><div className="mx-auto max-w-xl"><div className="no-print mb-5 text-center"><h1 className="page-title">Etiqueta do aparelho</h1><p className="page-subtitle">Pré-visualização em escala ampliada</p></div><div className="mx-auto aspect-[58/40] w-full max-w-[580px] overflow-hidden rounded-xl bg-white p-[6%] text-black shadow-2xl print:w-[58mm] print:rounded-none print:p-[3mm] print:shadow-none"><div className="flex items-start justify-between border-b-2 border-black pb-2"><div><strong className="text-[clamp(15px,3vw,26px)] leading-none">CELLSHOP</strong><p className="mt-1 text-[clamp(7px,1.4vw,11px)]">Tecnologia com procedência</p></div><strong className="text-[clamp(15px,3vw,25px)]">{brl.format(Number(unit.salePrice))}</strong></div><div className="py-[4%]"><h2 className="text-[clamp(16px,3.5vw,28px)] font-black leading-tight">{unit.productVariant.model}</h2><p className="text-[clamp(10px,2vw,16px)] font-semibold">{unit.productVariant.storage} · {unit.productVariant.color} · {unit.condition==="NEW"?"Novo":"Seminovo"}</p></div><Barcode value={unit.internalCode}/><div className="mt-1 flex justify-between font-mono text-[clamp(7px,1.4vw,11px)]"><span>IMEI {unit.imei1}</span><span>{unit.serialNumber??""}</span></div></div></div></>}
