ALTER TABLE "Technician" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Technician" FORCE ROW LEVEL SECURITY;

ALTER TABLE "ServiceOrder" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ServiceOrder" FORCE ROW LEVEL SECURITY;

ALTER TABLE "ServiceOrderHistory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ServiceOrderHistory" FORCE ROW LEVEL SECURITY;

ALTER TABLE "ServiceChecklistItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ServiceChecklistItem" FORCE ROW LEVEL SECURITY;

ALTER TABLE "ServiceDiagnostic" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ServiceDiagnostic" FORCE ROW LEVEL SECURITY;

ALTER TABLE "ServiceQuote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ServiceQuote" FORCE ROW LEVEL SECURITY;

ALTER TABLE "ServiceQuoteItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ServiceQuoteItem" FORCE ROW LEVEL SECURITY;

ALTER TABLE "Part" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Part" FORCE ROW LEVEL SECURITY;

ALTER TABLE "PartCompatibility" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PartCompatibility" FORCE ROW LEVEL SECURITY;

ALTER TABLE "PartMovement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PartMovement" FORCE ROW LEVEL SECURITY;

ALTER TABLE "ServiceOrderPart" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ServiceOrderPart" FORCE ROW LEVEL SECURITY;

ALTER TABLE "ServiceOrderPayment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ServiceOrderPayment" FORCE ROW LEVEL SECURITY;

ALTER TABLE "ServiceAttachment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ServiceAttachment" FORCE ROW LEVEL SECURITY;
