import Link from "next/link";
import { Plus, Printer, Search, Smartphone } from "lucide-react";
import { Flash } from "@/components/flash";
import { brl, dateTime } from "@/lib/format";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";
const statusLabel:Record<string,string>={AVAILABLE:"Disponível",RESERVED:"Reservado",SOLD:"Vendido",SERVICE:"Assistência",DEFECTIVE:"Defeituoso",RETURNED:"Devolvido",TRADE_IN_PROCESS:"Em avaliação",INACTIVE:"Inativo"};
export default async function StockPage({searchParams}:{searchParams:Promise<{q?:string;ok?:string;erro?:string}>}){
  const {q="",ok,erro}=await searchParams;
  const units=await prisma.inventoryUnit.findMany({where:{deletedAt:null,...(q?{OR:[{internalCode:{contains:q,mode:"insensitive"}},{imei1:{contains:q}},{serialNumber:{contains:q,mode:"insensitive"}},{productVariant:{model:{contains:q,mode:"insensitive"}}}]}:{})},include:{productVariant:true},orderBy:{createdAt:"desc"},take:100});
  return <><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><h1 className="page-title">Estoque</h1><p className="page-subtitle">Cada aparelho acompanhado individualmente.</p></div><Link href="/estoque/novo" className="btn-primary"><Plus size={18}/>Cadastrar aparelho</Link></div><Flash ok={ok} error={erro}/><div className="card overflow-hidden"><form className="flex gap-3 border-b border-[#28282d] p-4"><div className="relative max-w-lg flex-1"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-600" size={17}/><input className="input pl-11" name="q" defaultValue={q} placeholder="Buscar por modelo, IMEI, serial ou código..."/></div><button className="btn-secondary">Buscar</button></form>{units.length===0?<div className="grid min-h-72 place-items-center text-center"><div><Smartphone className="mx-auto text-zinc-700" size={38}/><p className="mt-3 font-semibold text-zinc-400">Nenhum aparelho encontrado</p><p className="mt-1 text-sm text-zinc-600">Cadastre uma unidade ou altere sua busca.</p></div></div>:<div className="table-wrap"><table className="data-table"><thead><tr><th>Aparelho</th><th>Código / IMEI</th><th>Condição</th><th>Entrada</th><th>Preço</th><th>Status</th><th></th></tr></thead><tbody>{units.map(unit=><tr key={unit.id}><td><p className="font-semibold text-white">{unit.productVariant.model} · {unit.productVariant.storage}</p><p className="mt-1 text-xs text-zinc-600">{unit.productVariant.color}</p></td><td><p>{unit.internalCode}</p><p className="mt-1 font-mono text-xs text-zinc-600">{unit.imei1}</p></td><td>{unit.condition==="NEW"?"Novo":"Seminovo"}{unit.batteryHealth?` · ${unit.batteryHealth}%`:""}</td><td>{dateTime.format(unit.createdAt)}</td><td className="font-semibold">{brl.format(Number(unit.salePrice))}</td><td><span className={unit.status==="AVAILABLE"?"badge badge-green":unit.status==="SOLD"?"badge badge-orange":"badge badge-red"}>{statusLabel[unit.status]}</span></td><td><Link href={`/estoque/${unit.id}/etiqueta`} title="Imprimir etiqueta" className="inline-grid size-9 place-items-center rounded-lg border border-[#303036] text-zinc-400 hover:text-white"><Printer size={16}/></Link></td></tr>)}</tbody></table></div>}</div></>;
}
